---
title: "Paige Duffin Data Analysis Project"
subtitle: "Working title- will give proper title later"
author: Paige Duffin
institute: "University of Georgia"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
output:
  bookdown::word_document2: 
    toc: false
bibliography: ../references.bib
csl: ../apa.csl
---

# Summary/Abstract
_Write a summary of your project._

# Introduction (required for part 1)

## General Background Information
Outbreaks of infectious disease are an important, yet poorly understood, driving force in population biology and, while prevalent in both terrestrial and marine systems, the manner by which outbreaks influence biotic relationships, age demographics, community structure and function, and trophic interactions in the aquatic realm consistently lags behind that of terrestrial disease ecology. The growing body of evidence in this field, however, supports the observation that marine disease epidemics are increasing in frequency and severity (Orth et al., 2006; Waycott et al., 2009). Elucidating the relationship between aquatic species and their pathogenic diseases is pertinent in the field of marine ecology because infection outbreaks have the potential to drastically alter ecosystem functionality (Blakesley et al., 2002; Burge et al., 2013). Many of the organisms which have faced chronic and/or severe outbreaks of disease (such as sea urchins, scleractinian corals and seagrasses) are also considered keystone species and/or ecosystem engineers, meaning that they contribute highly valuable services or functions to their surrounding community and ecosystem. Thus, it comes as no surprise that disease-driven mass mortalities of these species often generate waves of ecological permutation, ranging from temporary local disruptions to permanent phase shifts (Burge et al., 2013), such as the transformation from a coral to macroalgal dominated Caribbean reef structure that accompanied the massive _Diadema antillarum_ (black sea urchin) die-off of the early 1980s (Lessios et al., 1984; Lessios, 1988). This event, likely caused by a biological pathogen (Schultz et al., 2016), reduced Diadema populations to less than 1% of their original size (Lessios, 1988). Mass mortality events impacting critical foundation species, ecosystem engineers, or keystone species such as the black sea urchin have been coined ‘marine disease emergencies’ due to the detrimental cascade of events that often succeeds them (Miner et al., 2018). 

Sea Star Wasting Disease (SSWD) is another epizootic crisis facing modern day coastal ecosystems. Outbreaks of asteroid wasting have been documented periodically since the late 1970s and SSWD describes a suite of symptoms observed across a broad range of sea star species, most of which play integral parts in shaping their community structure. Generally speaking, the wasting disease events which punctuated the past four decades were relatively brief, in localized areas, and largely failed to capture the attention of the scientific community. Beginning in summer 2013, however, mass mortalities of sea stars due to wasting disease have caused unprecedented damage, owing to the geographical and temporal extent of impact. This ongoing epizootic, which has killed millions of asteroids across over 20 taxa, is widely referred to as the largest disease event sweeping through a wildlife marine species in documented history (Hewson et al. 2014, Gudenkauf & Hewson, 2015, Eisenlord et al. 2016). 


## Description of data and data source
_Describe what the data is, what it contains, where it is from, etc._

### The Source
The vast majority of disease documentation and surveys cover the west coast of the United States. While it is almost certainly true that SSWD is most prevalent in this region, there is a strong bias towards the discovery of diseased organisms owing to the emphasis of long-term survey networks in the area, such as the extensive [Multi-Agency Rocky Intertidal Network](https://marine.ucsc.edu/index.html) (MARINe for short). The vast majority of what we know about SSWD dynamics comes from studies along the Pacific Coast of North America using data produced through the combined effort of dedicated scientists, government agencies, and local citizens. The purpose of this investigation is to make use of this data monitoring system to investigate spatial and temoporal changes in sea star abundance along the west coast of the United States. 

### The Data
Below I explore the raw data I downloaded from a link I recieved after submitting a request for the data on the MARINe webpage.

```{r}
library(readr)
raw_SS_count <- read.csv("~/Documents/GitHub/PaigeDuffin-Project/data/raw_data/seastarkat_size_count_totals_download.csv")
head(raw_SS_count, 3)
levels(raw_SS_count$georegion)
levels(raw_SS_count$species_code)
```

Notably, it contains the following information (some parameters removed from this overview): 

* `groupcode`: The unique code for each monitoring group
* `marine_site_name`: The name of the site where the survey was conducted.
* `latitude` and `longitude`: (self explanatory)
* `marine_season_code`: A four-character code to identify the Sampling season. The first two characters indicate the season and the last 2 characters indicate the year.
* `method_code`: The method used for sampling the plot. 
* `size_bin`: The size of the species being counted, binned to the nearest 5 or 10 millimeter.
* `target_assemblage`: The specific organism that this transect was created to monitor.
* `total`: Total number of individuals counted in a given size_bin
* `mpa_designation`: Describes whether the referenced site is located within a Marine Protected Area (MPA) or is a reference site. If this field is blank, the referenced site is not located within an MPA, or is not a reference site for an existing MPA site.
* `georegion`/ `bioregion`: geographic/biogeographic region in which site is located
* `state_province`: The State or Province and Country where the referenced site is located.
* `island`: The name of the island where the referenced site is located. Sites not on islands are designated as mainland.

### Additional Data Sources 
I believe I have more data coming in to work with. I recieved an email today from a representative of the Multi-Agency Rocky Intertidal Network. This email said:

> _"You should have been able to download our sea star size/count data from the data download page that you were directed to after filling out the data request form. We also have associated disease category data, but because we only sample 1x per year at most sites, this additional info will not give you an idea of disease emergence or progression within a site or region. You might also be interested in our observation data set, which would be better for these types of questions. We can have this data to you within about a week."_

I'm also interested in environmental data such as sea surface temperature, dissolved oxygen, salinity, etc., as SSWD is thought to be exacerbated by abiotic stressors. However, I'm having a difficult time finding data to use that will pair reasonably well with the dates and locations of the `raw_SS_count` data I know I will be working with. 

I'm very interested in this disease and environmental data, but don't know what it will look like or if it will be feasible to use. Hopefully, I can incorporate this into my analysis, but for right now I am going to focus on outlining the questions I can answer with the data I have in hand. 

## Questions/Hypotheses to be addressed
_State the research questions you plan to answer with this analysis_

**1. Are sea star populations changing over time?** 
I anticipate that there will be a decline in sea star populations over time, but that the change will not occur uniformly across geographical regions and species. Species that are reported to have been affected by SSWD will experience the biggest declines. 

**2. Is species composition uniform across space?**
I expect to be able to define rough species ranges. 

**3. Is there evidence of sampling bias?**
  Is there a relationship between important survey parameters (mainly, abundance data) and sampling method (ex. group conducting the survey, plot sampling method, the target assemblage). At the very least, I expect there will be bias based on the targeted organism of the survey; if a given survey aims to characterize the presence of one species of sea stars, it is likely that they will seek out that species and record higher counts. 

### Questions I may be able to answer with disease and/or environmental data:

**1. Is there a relationship between sea star abundance over time and prevalence of SSWD?**
There absolutely should be a relationship, based on the body of evidence presented on studies that have focused on individual species. 

**2. Are there species of sea stars that are more affected by disease than others?**
The literature implies that this may be the case, but there also may be a bias based on species that researchers are more interested in. 

**3. Are there regions that are more affected by disease than others, regardless of species?**
The most recent epidemic appears to be so widespread that I suspect there won't be any significant trends here, but it's certainly worth checking.  

**4. Is there a relationship between sea star wasting disease and dissolved oxygen levels?**
A recent, but leading hypothesis in the field of SSWD suggests that it may be triggered specifically by low oxygen conditions. I'm very interested in exploring relationships between SSWD and DO levels- this is actually the main curiosity that lead me to focus in on this data set. 

**5. Is there a relationship between sea star wasting disease and [other water quality parameters I'm able to find data for]?**


# Methods and Results

_In most research papers, results and methods are separate. You can combine them here if you find it easier. You are also welcome to structure things such that those are separate sections._


## Data aquisition
_As applicable, explain where and how you got the data. If you directly import the data from an online source, you can combine this section with the next._

## Data import and cleaning
_Write code that reads in the file and cleans it so it's ready for analysis. Since this will be fairly long code for most datasets, it might be a good idea to have it in one or several R scripts. If that is the case, explain here briefly what each file does. The files themselves should be commented well so everyone can follow along._

## Univariate analysis
_Use a combination of text/tables/figures to explore and describe your data. You should produce plots or tables or other summary quantities for most of your variables. You definitely need to do it for the important variables, i.e. if you have main exposure or outcome variables, those need to be explored. Depending on the total number of variables in your dataset, explore all or some of the others._

## Bivariate analysis
_Create plots or tables and compute simple statistics (e.g. t-tests, simple regression model with 1 predictor, etc.) to look for associations between your outcome(s) and each individual predictor variable_


## Full analysis
_Use one or several suitable statistical/machine learning methods to analyze your data and to produce meaningful figures, tables, etc. This might again be code that is best placed in one or several separate R scripts that need to be well documented. You can then load the results produced by this code_

# Discussion

## Summary and Interpretation
_Summarize what you did, what you found and what it means._

## Strengths and Limitations
_Discuss what you perceive as strengths and limitations of your analysis._

## Conclusions
_What are the main take-home messages?_


_Include citations in your Rmd file using bibtex, the list of references will automatically be placed at the end_

# References

