---
title: "Untitled"
author: "Paige Duffin"
date: "10/9/2019"
output: html_document
---

```{r message=FALSE}
library(caret) # Classification and Regression Training
library(corrplot)
library(dplyr) # A Grammar of Data Manipulations
library(forcats) # Tools for Working with Categorical Variables (Factors)
library(gdata) # Various R Programming Tools for Data Manipulation
library(ggplot2) # Create Elegant Data Visualizations Using the Grammar of Graphics
library(ggrepel) # Automatically Position Non-Overlapping Text Labels with ‘ggplot2’
library(ggridges) # Ridgeline Plots in ‘ggplot2’
library(ggthemes) # Extra Themes, Scales, and Geoms for ‘ggplot2’
library(gmodels) # Various R Programming Tools for Model Fitting
library(grid) # The Grid Graphics Package
library(gridExtra)
library(knitr) # A General-Purpose Package for Dynamic Report Generation in R
library(lmtest) # Testing Linear Regression Models
library(plyr) # Tools for Splitting, Applying and Combining Data
library(purrr) # Functional Programming Tools
library(readr) # Read Rectangular Text Data
library(rpart)
library(rattle)
library(scales) # Scale Functions for Visualization
library(shiny) # Web Application Framework for R
library(skimr) # Compact and Flexible Summaries of Data
library(stringr) # Simple, Consistent Wrappers for Common String Operations
library(tibble) # Simple Data Frames
library(tidyr) # Easily Tidy Data with ‘spread()’ and ‘gather()’ Functions
library(tidyverse) # Install and Load ‘Tidyverse’ Packages
library(usmap)
library(rworldmap)
library(ggmap)
library(maps)
library(mapdata)
library(cowplot)
library("googleway")
library("ggspatial") 
library("rnaturalearth") 
library("rnaturalearthdata")
theme_set(theme_bw())
library("sf")
register_google(key = "AIzaSyB3n0SkJTXxrbUkF2bkBJs7XdleT_iJXsg", write = TRUE)
```

```{r}
raw_SS_count <- read.csv("~/Documents/GitHub/PaigeDuffin-Project/data/raw_data/seastarkat_size_count_totals_download.csv")
head(raw_SS_count, 3)
```

```{r}
unique_sites <- subset(raw_SS_count, !duplicated(raw_SS_count$site_code)) 
sites_coordinates <- unique_sites[c(2,5:6,22)]
sites_coordinates_contig <- filter(sites_coordinates, sites_coordinates$state_province != "Alaska") 

CA_coordinates <- filter(sites_coordinates, sites_coordinates$state_province == "California")
OR_coordinates <- filter(sites_coordinates, sites_coordinates$state_province == "Oregon")
WA_coordinates <- filter(sites_coordinates, sites_coordinates$state_province == "Washington")
AK_coordinates <- filter(sites_coordinates, sites_coordinates$state_province == "Alaska")

CA_coordinates <- as.data.frame(CA_coordinates)
OR_coordinates <- as.data.frame(OR_coordinates)
WA_coordinates <- as.data.frame(WA_coordinates)
AK_coordinates <- as.data.frame(AK_coordinates)
```


```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```

```{r}
plot_usmap(include = c("CA","OR","WA","AK"))
```

```{r}
AK_zoom1 <- ggplot(data = world) +
    geom_sf() +
  geom_point(data= sites_coordinates,aes(x=sites_coordinates$longitude, y=sites_coordinates$latitude,), size = 2, alpha = 0.4) +
  annotation_scale(location = "bl", width_hint = 0.3) +
  coord_sf(xlim = c(-170, -128), ylim = c(54, 72), expand = FALSE) + 
  xlab("Longitude") + 
  ylab("Latitude") + 
  scale_x_continuous(breaks = c(-160, -150, -140))
  

AK_zoom2 <- ggplot(data = world) +
    geom_sf() +
  geom_point(data= sites_coordinates,aes(x=sites_coordinates$longitude, y=sites_coordinates$latitude,), size = 2, alpha = 0.4) +
  annotation_scale(location = "bl", width_hint = 0.3) +
  coord_sf(xlim = c(-144, -130), ylim = c(55, 62), expand = FALSE) + 
  xlab("Longitude") + 
  ylab("Latitude") + 
  scale_x_continuous(breaks = c(-142, -138, -134))
  
grid.arrange(AK_zoom1, AK_zoom2, ncol = 2)
```

```{r}
State <- sites_coordinates_contig$state_province
ggplot(data = world) +
    geom_sf() +
  geom_jitter(data= sites_coordinates_contig,aes(x=sites_coordinates_contig$longitude, y=sites_coordinates_contig$latitude,col=State), size = 2, alpha = 0.6, width = 0.2) +
  annotation_scale(location = "bl", width_hint = 0.3) +
  coord_sf(xlim = c(-128, -115), ylim = c(32, 49.5), expand = FALSE) + 
  xlab("Longitude") + 
  ylab("Latitude")
```

# CA SITES
```{r}
CA_map <- ggplot(data = world) +
    geom_sf() +
  geom_point(data= CA_coordinates,aes(x=CA_coordinates$longitude, y=CA_coordinates$latitude,col=), size = 3, alpha = 0.4) +
  coord_sf(xlim = c(-130, -115), ylim = c(32, 42.5), expand = FALSE)
CA_map
```


```{r}
CA <- states %>%
  filter(region %in% c("california"))
CA_plot <- ggplot(data = CA) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "palegreen", color = "black") + coord_quickmap()
OR <- states %>%
  filter(region %in% c("oregon"))
OR_plot <- ggplot(data = OR) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "palegreen", color = "black") + coord_quickmap()
WA <- states %>%
  filter(region %in% c("washington"))
WA_plot <- ggplot(data = WA) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "palegreen", color = "black") + coord_quickmap()

```

```{r}

```


```{r}
WA_plot +
  geom_point(data= sites_coordinates,aes(x=sites_coordinates$longitude, y=sites_coordinates$latitude,), size = 3, alpha = 0.6) +
  coord_sf(xlim = c(-126, -116), ylim = c(45, 49.5), expand = FALSE) 
```






```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
AK_zoom1 <- ggplot(data = world) +
    geom_sf() +
  geom_point(data= sites_coordinates,aes(x=sites_coordinates$longitude, y=sites_coordinates$latitude,), size = 2, alpha = 0.4,  color ="darkgoldenrod1") +
  annotation_scale(location = "bl", width_hint = 0.3) +
  coord_sf(xlim = c(-170, -128), ylim = c(54, 72), expand = FALSE) + 
  xlab("Longitude") + 
  ylab("Latitude") + 
  scale_x_continuous(breaks = c(-160, -150, -140))
  

AK_zoom2 <- ggplot(data = world) +
    geom_sf() +
  geom_point(data= sites_coordinates,aes(x=sites_coordinates$longitude, y=sites_coordinates$latitude,), size = 4, alpha = 0.4, color ="firebrick3") +
  annotation_scale(location = "bl", width_hint = 0.3) +
  coord_sf(xlim = c(-144, -130), ylim = c(55, 62), expand = FALSE) + 
  xlab("Longitude") + 
  ylab("Latitude") + 
  scale_x_continuous(breaks = c(-142, -138, -134))
  
grid.arrange(AK_zoom1, AK_zoom2, ncol = 2)
```