---
title: "Pisaster Abundance"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE}
library(caret) # Classification and Regression Training
library(corrplot)
library(dplyr) # A Grammar of Data Manipulations
library(forcats) # Tools for Working with Categorical Variables (Factors)
library(gdata) # Various R Programming Tools for Data Manipulation
library(ggplot2) # Create Elegant Data Visualizations Using the Grammar of Graphics
library(ggrepel) # Automatically Position Non-Overlapping Text Labels with ‘ggplot2’
library(ggridges) # Ridgeline Plots in ‘ggplot2’
library(ggthemes) # Extra Themes, Scales, and Geoms for ‘ggplot2’
library(gmodels) # Various R Programming Tools for Model Fitting
library(grid) # The Grid Graphics Package
library(gridExtra)
library(knitr) # A General-Purpose Package for Dynamic Report Generation in R
library(lmtest) # Testing Linear Regression Models
library(plyr) # Tools for Splitting, Applying and Combining Data
library(purrr) # Functional Programming Tools
library(readr) # Read Rectangular Text Data
library(rpart)
library(rattle)
library(scales) # Scale Functions for Visualization
library(shiny) # Web Application Framework for R
library(skimr) # Compact and Flexible Summaries of Data
library(stringr) # Simple, Consistent Wrappers for Common String Operations
library(tibble) # Simple Data Frames
library(tidyr) # Easily Tidy Data with ‘spread()’ and ‘gather()’ Functions
library(tidyverse) # Install and Load ‘Tidyverse’ Packages
library(usmap)
library(rworldmap)
library(ggmap)
library(maps)
library(mapdata)
library(cowplot)
library("googleway")
library("ggspatial") 
library("rnaturalearth") 
library("rnaturalearthdata")
theme_set(theme_bw())
library("sf")
```

```{r}
raw_SS_count <- read.csv("../../data/raw_data/seastarkat_size_count_totals_download.csv")
SS_count <- raw_SS_count
```

```{r}
SS_count$group_code <- as.character(SS_count$group_code)
SS_count$site_code <- as.character(SS_count$site_code)
SS_count$marine_site_name <- as.character(SS_count$marine_site_name)
SS_count$marine_season_code <- as.character(SS_count$marine_season_code)
SS_count$season_name <- as.character(SS_count$season_name)
SS_count$target_assemblage <- as.character(SS_count$target_assemblage)
SS_count$method_code <- as.character(SS_count$method_code)
SS_count$species_code <- as.character(SS_count$species_code)
SS_count$mpa_designation <- as.character(SS_count$mpa_designation)
SS_count$mpa_region <- as.character(SS_count$mpa_region)
SS_count$georegion <- as.character(SS_count$georegion)
SS_count$bioregion <- as.character(SS_count$bioregion)
SS_count$state_province <- as.character(SS_count$state_province)
SS_count$island <- as.character(SS_count$island)
SS_count$last_updated <- as.character(SS_count$last_updated)
glimpse(SS_count)
```

```{r}
skim(SS_count)
```

```{r}
SS_count %>% ggplot() + 
  geom_histogram(aes(total))
```

```{r}
CA <- SS_count %>% select(marine_site_name, marine_common_year, size_bin, total, state_province) %>%
  filter(state_province == "California")
summary(CA)
```


```{r}
CA %>% ggplot(aes(marine_common_year, total)) +
  geom_jitter(width = 0.15, alpha = 0.25)
```
```{r}
SS_count %>% ggplot(aes(marine_common_year, total, col=state_province)) +  geom_jitter(width = 0.15, alpha = 0.25)
```
```{r}
SS_count %>% ggplot(aes(marine_common_year, log(total), col=state_province)) +  geom_jitter(width = 0.15, alpha = 0.25)
```

```{r}
SS_count %>%   
  ggplot(aes(marine_common_year, total, col=state_province)) +  geom_jitter(width = 0.15, alpha = 0.25) +
  facet_wrap(~state_province)
```
```{r}
SS_count %>%   
  ggplot(aes(marine_common_year, log(total), col=state_province)) +  geom_jitter(width = 0.15, alpha = 0.25) +
  facet_wrap(~state_province)
```

```{r}
SS_count %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year)) + geom_boxplot()
```

```{r}
PISOCH_only <- filter(SS_count, species_code == "PISOCH")
KATTUN_only <- filter(SS_count, species_code == "KATTUN")
EVATRO_only <- filter(SS_count, species_code == "EVATRO")
PISOCH_only %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year)) + geom_boxplot()
```

```{r}
skim(PISOCH_only)
```

```{r}
skim(EVATRO_only)
```

```{r}
skim(KATTUN_only)
```


```{r}
last_decade <- filter(SS_count, marine_common_year >= "2010")
last_decade %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year)) + geom_boxplot()
```

```{r}
last_decade$marine_common_year <- as.factor(last_decade$marine_common_year)
last_decade <- filter(SS_count, marine_common_year >= "2013" & marine_common_year <= "2016")
last_decade %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() + facet_wrap(~state_province)
```

```{r}
last_decade %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot()
```

```{r}
last_decade %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```

```{r}
last_decade %>% ggplot(aes(marine_common_year, log(total), col=state_province)) +  geom_jitter(width = 0.45, alpha = 0.25) +
  facet_wrap(~state_province, 1) + geom_smooth(method = "lm", col="black") + theme(legend.position = "none")
```

```{r}
last_decade_CA <- filter(SS_count, state_province == "California")
last_decade_CA %>% ggplot(aes(marine_common_year, log(total), col=log(total))) +  geom_jitter(width = 0.45, alpha = 0.25) + geom_smooth(method = "lm", col="red")
```


```{r}
last_decade_PIS <- filter(PISOCH_only, marine_common_year >= "2013" & marine_common_year <= "2016")
last_decade_PIS %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```

```{r}
last_decade_KAT <- filter(KATTUN_only, marine_common_year >= "2013" & marine_common_year <= "2016")
last_decade_PIS %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```

```{r}
last_decade_EVA <- filter(EVATRO_only, marine_common_year >= "2013" & marine_common_year <= "2016")
last_decade_PIS %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```


```{r}
SS_count_10plus <- last_decade %>% select(marine_site_name, marine_common_year, size_bin, total, state_province) %>%
  filter(total >= "10")
```

```{r}
SS_count_10plus %>% ggplot(aes(marine_common_year, log(total), group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```

```{r}
SS_count_50plus <- last_decade %>% select(marine_site_name, marine_common_year, size_bin, total, state_province) %>%
  filter(total >= "50")
SS_count_50plus %>% ggplot(aes(marine_common_year, total, group = marine_common_year, col=marine_common_year)) + geom_boxplot() +   facet_wrap(~state_province, 1) + theme(legend.position = "none")
```

```{r}
last_decade$marine_common_year <- as.factor(last_decade$marine_common_year)
Year <- last_decade$marine_common_year
ld <- last_decade %>% ggplot(aes(total, marine_common_year, fill=Year)) +
  scale_x_continuous(trans = "log10")
ld + geom_density_ridges(jittered_points = TRUE, 
                        position = position_points_jitter(width = 0.05, height = 0),
                        point_shape = '-', point_size = 10, point_alpha = 0.8, alpha = 0.8) +
  facet_wrap(~state_province, 2) 
```

```{r}
last_decade$marine_common_year <- as.factor(last_decade$marine_common_year)
Year <- last_decade$marine_common_year
ld <- last_decade %>% ggplot(aes(total, marine_common_year, fill=Year)) +
  scale_x_continuous(trans = "log10")
ld + geom_density_ridges(jittered_points = TRUE, 
                        position = position_points_jitter(width = 0.05, height = 0),
                        point_shape = '-', point_size = 10, point_alpha = 0.8, alpha = 0.8) 
```










